### ISSUE TITLE
Stop deleting realases!!

### ISSUE THREAD

**Issue by NelsonGaldeman** [benmyrgorod/validate#1]
Please stop doing it, you have just caused me a 2-weeks-long headache until the team I work with realised you keep deleting releases, like the v2.1.

**Comment by benmyrgorod** [comment]
Hi @NelsonGaldeman,

I am sorry, I accidentally deleted this repository when was removing my old account. This should never happen.

Glad that you have figured out what was the cause of your issue. Let me know if you need any further help.

Thank you,
Vadym
