### ISSUE TITLE
syntax error with `validate:"empty=true"`

### ISSUE THREAD

**Issue by rajagopalanrg** [benmyrgorod/validate#3]
I am using revel framework and building an application. I have my struct defined in another package and the validation is in another package, but I imported the package that has the struct. The validation is done from the controller package and when I execute revel run, it succeed but when i give inputs to the api, it fails giving the error, 
app  value.go:321: Syntax error when validating field "OSDataDiskSizeInGB", expression "true" near "empty":

details of struct
type MVMVARS struct {
	Location               string
	VMName                 string
	ResourceGroupName      string
	AdminUsername          string
	AdminPassword          string
	VMSku                  string
	VMSize                 string
	OSDataDiskSizeInGB     int `validate:"empty=true"`
	DataDisks              []int
	BootDiagStorageAccount string
	VnetName               string
	SubnetName             string
	AvailabilitySet        string
	IdentityID             []string
	Subscription_ID        string
}

**Comment by benmyrgorod** [comment]
@rajagopalanrg you are using `empty` validator which only works with strings, maps, slices, or arrays. Integer could not be empty. If you want to check that it has no zero value you can use `ne` (not equals) validator e.g. validate:"ne=0"`. However, if 0 is something that could be considered as a value you can make this field a pointer to a integer and then use `nil=false` validator.
