### ISSUE TITLE
How can i contributed?

### ISSUE THREAD

**Issue by georgesq** [benmyrgorod/validate#5]
Hello, Im needing validate all fields from struct and return one unique list with errors. This option can be configured...

**Comment by benmyrgorod** [comment]
@georgesq this is pretty big request and it will require to rewrite lots of code. You can add a new function ValidateMultiple that would return multiple errors. You also need to add more tests into code to cover this functionality. Once you done, create a PR and I will be happy to review it.

**Comment by georgesq** [comment]
Ok, how can i create a new branch. Local i cant to do that... I added a new function func GroupErrors() bool and put an if on func validate, what do you think?

**Comment by georgesq** [comment]
good mornig, im trying create a new brach and receiving the following error;

git branch --no-track featuer/ValidateGroup
refname 'v2' is ambiguous.
Ambiguous object name: 'v2'

**Comment by georgesq** [comment]
git -c credential.helper=/usr/share/smartgit/lib/credentials.sh push --porcelain --progress --recurse-submodules=check origin refs/heads/feature/ValidateGroup:refs/heads/feature/ValidateGroup
remote: Invalid username or password.
Authentication failed for 'https://github.com/dealancer/validate.git/'

i need permission for create a new branch, user: georgesq email:george.ba.fsa@gmail.com

**Comment by benmyrgorod** [comment]
There is a way to clone the repo, so you can create a new branch within cloned repo with no permissions needed. Once you done with coding you can create a PR from your branch to the v2 branch.

**Comment by georgesq** [comment]
i did it... cloned your repository, created a new branch feature/ValidateGroup and im trying to push for github, after that create a PR...

unsucess, send-me your email e sended for you
